language: rust
rust: nightly
sudo: false
os: osx

matrix:
  include:
    - osx_image: xcode6.4
    - osx_image: xcode7.3
    - osx_image: xcode8
    - osx_image: xcode8.3
    - osx_image: xcode9
    - osx_image: xcode9.1
    - osx_image: xcode9.2
    - osx_image: xcode9.3
script:
  - cargo run -p wasm-bindgen-cli --release --bin wasm-bindgen -- --help
